name: Generate Snake Animation

on:
  # Run this workflow automatically on a schedule
  schedule:
    - cron: '0 */12 * * *' # Runs every 12 hours

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Create dist directory
        run: mkdir -p dist
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          # Your GitHub username
          github_user_name: ${{ github.repository_owner }}

          # The output files for the animation
          # Generates a light and dark mode version
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
      - name: Push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "chore: update snake animation"
          add: "dist/*"